### ISSUE TITLE
Grate!

### ISSUE THREAD

**Issue by Soprani** [zanadu/ImageCropView#1]
Hi!

Like your solution, a lot.
But, auto layout and scrollview is a mess in iOS and makes it hard to make the view universal.

Keep up the good work
/olle

**Comment by Soprani** [comment]
To solve unexpected behaviour, when using Autolayout, move the setup from viewDidLoad() to viewDidLayoutSubviews().

/olle

**Comment by peyotll** [comment]
oops! I guess I released it too fast... I will change the example.
Thanks for opening an issue!
